#!/bin/sh
set -eu

BLOCKLIST_URL="${BLOCKLIST_URL:-http://ddos-agent.ddos-protection.svc.cluster.local:8080/blocklist.txt}"
SYNC_INTERVAL="${BLOCKLIST_SYNC_INTERVAL_SECONDS:-15}"
BLOCKLIST_MAP_PATH="/etc/nginx/ddos/blocked_ips.map"

mkdir -p /etc/nginx/ddos
[ -f "$BLOCKLIST_MAP_PATH" ] || printf "# empty\n" > "$BLOCKLIST_MAP_PATH"

update_blocklist_map() {
  tmp_txt="/tmp/blocked_ips.txt"
  tmp_map="/tmp/blocked_ips.map"

  if ! curl -fsS --max-time 3 "$BLOCKLIST_URL" -o "$tmp_txt"; then
    return 1
  fi

  {
    echo "# generated by docker-entrypoint.sh"
    sed 's/\r$//' "$tmp_txt" \
      | awk 'NF {print $1}' \
      | grep -E '^[0-9]+(\.[0-9]+){3}$' \
      | sort -u \
      | sed 's/\./\\./g' \
      | awk '{printf("~^%s$ 1;\n", $0)}'
  } > "$tmp_map"

  mv "$tmp_map" "$BLOCKLIST_MAP_PATH"
  return 0
}

update_blocklist_map || true

(
  while true; do
    sleep "$SYNC_INTERVAL"
    if update_blocklist_map; then
      nginx -s reload >/dev/null 2>&1 || true
    fi
  done
) &

exec nginx -g 'daemon off;'
