# {{- $svcMon := .Values.backend.serviceMonitor }}
# {{- if $svcMon.enabled }}
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: employee-leave-backend-monitor
#   namespace: {{ default "monitoring" $svcMon.namespace }}
#   labels:
#     release: {{ default "monitoring" $svcMon.releaseLabel }}
# spec:
#   selector:
#     matchLabels:
#       app: employee-leave-backend
#   namespaceSelector:
#     matchNames:
#       - {{ .Values.namespace }}
#   endpoints:
#     - port: {{ default "http" $svcMon.portName }}
#       path: {{ default "/metrics" $svcMon.path }}
#       interval: {{ default "15s" $svcMon.interval }}
# {{- end }}
