{
 "title": "Leave App Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (\r\n  count_over_time(\r\n    {namespace=\"ingress-nginx\"} \r\n    |~ \"cosmin-employee-leave\\\\.bench\\\\.az\\\\.am-isd\\\\.com\"\r\n    | regexp \"client_ip\\\":\\\"(?P<client_ip>[0-9.]+)\\\".*\\\"status\\\":(?P<status>[0-9]+)\"\r\n    [$__range]\r\n  )\r\n)\r\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "trafic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (client_ip) (\r\n  count_over_time(\r\n    {namespace=\"ingress-nginx\"} \r\n    |= \"client_ip\" \r\n    | regexp \"client_ip\\\":\\\"(?P<client_ip>[0-9.]+)\"\r\n    |= \"cosmin-employee-leave.bench.az.am-isd.com\"\r\n    [$__range]\r\n  )\r\n)\r\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "vizitatori",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (client_ip) (\r\n  count_over_time(\r\n    {namespace=\"ingress-nginx\"}\r\n    |~ \"host\\\":\\\"cosmin-employee-leave.bench.az.am-isd.com\\\"\"\r\n    !~ \"user_agent\\\":\\\"Blackbox Exporter\"\r\n    | regexp \"client_ip\\\":\\\"(?P<client_ip>[0-9.]+)\"\r\n    [$__range]\r\n  )\r\n))\r\n",
     "legendFormat": "{{clientip}}"
    }
   ]
  },
  {
   "title": "Ip and browser",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"ingress-nginx\"}\r\n|~ \"host\\\":\\\"cosmin-employee-leave.bench.az.am-isd.com\\\"\"\r\n!~ \"user_agent\\\":\\\"Blackbox Exporter\"\r\n| regexp \"client_ip\\\":\\\"(?P<client_ip>[0-9.]+).*user-agent\\\":\\\"(?P<user_agent>[^\\\"]+)\"\r\n"
    }
   ]
  },
  {
   "title": "ip uri care au accesat site ul",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(\r\n  sum by (client_ip) (\r\n    count_over_time(\r\n      {namespace=\"ingress-nginx\"}\r\n      |~ \"host\\\":\\\"cosmin-employee-leave.bench.az.am-isd.com\\\"\"\r\n      !~ \"client_ip\\\":\\\"128\\\\.77\\\\.15\\\\.17\"\r\n      | regexp \"client_ip\\\":\\\"(?P<client_ip>[0-9.]+)\"\r\n      [$__auto]\r\n    )\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "ip uri unice",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(\r\n  sum by (client_ip) (\r\n    count_over_time(\r\n      {namespace=\"ingress-nginx\"}\r\n      |~ \"host\\\":\\\"cosmin-employee-leave.bench.az.am-isd.com\\\"\"\r\n      !~ \"user-agent\\\":\\\"Blackbox Exporter\"\r\n      | regexp \"client_ip\\\":\\\"(?P<client_ip>[0-9.]+)\"\r\n      [$__range]\r\n    )\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "SSL - certificate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((max by (instance) (\r\n  probe_ssl_earliest_cert_expiry{instance=\"https://cosmin-employee-leave.bench.az.am-isd.com\"}\r\n) - time()) / 86400)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cererile de concediu pending",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 29 },
   "targets": [
    { "expr": "(active_leaves)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cererile de concediu aprobate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 29 },
   "targets": [
    { "expr": "max(leaves_approved_total)\r\n", "legendFormat": "{{aprove}}" }
   ]
  },
  {
   "title": "Cererile de concediu respinse",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 29 },
   "targets": [
    { "expr": "(leaves_rejected_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Număr total utilizatori",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(users_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}