apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leave-app-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pascariucosmin93/leave-app.git
    targetRevision: main
    path: kube-security
  destination:
    server: https://kubernetes.default.svc
    namespace: employee-leave-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
